### ISSUE TITLE
Bump up material-ui to v5

### ISSUE THREAD

**Issue by RusherRG** [Auto-DL/Auto-DL#409] opened 2021-10-03 19:59 UTC
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

Material-UI has released v5 recently. It would be better to bump up at an earlier stage of development itself. There will be a need to update all import statements currently being used for material-ui but shouldn't be that big of an issue.

**Comment by adithyapaib** [comment] 2021-10-04 03:22
If assigned I will update it

**Comment by RusherRG** [comment] 2021-10-04 05:04
@adithyapaib great thanks. I'm assigning you to this issue.

**Comment by akshay11298** [comment] 2021-10-17 05:45
Hey, if the issue is still open, I'd like to work on it

**Comment by Kathuria** [comment] 2021-10-30 04:04
@McTechie : I would like to take this.

**Comment by McTechie** [comment] 2021-10-30 05:31
@Kathuria  I've assigned this to you. If you do face any blockers, feel free to discuss here or on our Slack

**Comment by Kathuria** [comment] 2021-10-30 09:07
@McTechie : Its done, Can you please review the changes.
autodl-platform is now running on latest version of material-ui i.e. v5

Note: I haven't touched v1-react directory as its already having latest material version installed. Additionally facing issue
TypeError: Cannot read properties of undefined (reading 'drawer')
(anonymous function)
src/Components/MainApp/Layout.js:41

This is  known issue in material that is working fine for ts files but not js - So can be taken up separately. Additionally noticed below warnings that can be fixed in separate issue if its open!
src/Components/MainApp/Layout.js
  Line 1:17:  'useState' is defined but never used   no-unused-vars
  Line 1:27:  'useEffect' is defined but never used  no-unused-vars

src/Components/MainApp/Step2.js
  Line 120:9:  The 'getProjectId' function makes the dependencies of useEffect Hook (at line 2210) change on every render. To fix this, wrap the definition of 'getProjectId' in its own useCallback() Hook  react-hooks/exhaustive-deps

src/Components/ProfilePage/ProfileFieldBlock.js
  Line 50:9:  Unreachable code  no-unreachable
  Line 55:9:  Unreachable code  no-unreachable
  Line 60:9:  Unreachable code  no-unreachable
  Line 65:9:  Unreachable code  no-unreachable
  Line 68:9:  Unreachable code  no-unreachable

**Comment by McTechie** [comment] 2022-02-22 06:41
Resolved in PR #446 ✨

**Closed by McTechie** 2022-02-22 06:41 UTC
Labels: hacktoberfest, dependencies, NextJS, breaking change
